In [13]:
import pandas as pd

# 1. Define the file paths
# (Make sure to update the 'input_excel_path' if your input file is saved somewhere else or named differently)
input_excel_path = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Timesheet samples\Correct timesheets\Kjetil H - Månedsrapport juni 2026.xlsx"

template_admin_path = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\templates\Admin.xlsx"
template_absence_path = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\templates\Absense.xlsx"
template_overtime_path = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\templates\overtime.xlsx"

# 2. Load the Excel files into pandas DataFrames
# If you need to read a specific sheet, you can add the argument: sheet_name='Sheet1'
df_input = pd.read_excel(input_excel_path)
df_admin = pd.read_excel(template_admin_path)
df_absence = pd.read_excel(template_absence_path)
df_overtime = pd.read_excel(template_overtime_path)

# 3. Display the first few rows of the input data to verify it loaded correctly
print("Input Data Preview:")
display(df_input.head())

# Optional: preview the templates headers to understand their structure
print("\nAdmin Template Columns:", df_admin.columns.tolist())
print("Absence Template Columns:", df_absence.columns.tolist())
print("Overtime Template Columns:", df_overtime.columns.tolist())

Input Data Preview:

,"MÅNEDSRAPPORT, ADMINISTRASJON",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NAVN:,Kjetil Haga,NaN,NaN,LØNNR:,508,NaN,MÅNED:,Jun,ÅR:,2026
1,NaN,ARBEIDS TID,NaN,KOMMENTAR,TOTALT\nARBEIDEDE\nTIMER,AVVIK (kun\nv. Mnd.slønn),Hvorav\ntimer\navspasert,AVTALT\nOVERTIDSARBEIDE,NaN,SYK,FERIE
2,DATO,FRA,TIL,NaN,NaN,NaN,Timer,50 %,100 %,DAGER,NaN
3,Timer overført fra siste måned,NaN,NaN,NaN,20,Gjenværende feriedager,NaN,NaN,NaN,NaN,25
4,1,7,15,NaN,7.5,0,NaN,NaN,NaN,NaN,NaN

Admin Template Columns: ['Ee \nID', 'Name', 'Email address', 'Role', 'Delivered monthly \nreport \nYES/NO', 'Total overtime (hours)', 'Overtime hours for pay out (HOURLY\nrate \nWT 118', 'Overtime \nadd\n50%\nWT 425', 'Overtime\n add \n100%\nWT 426', 'Overtime hours \nfor  time off\nWT 61', 'Withdrawal of time off (avspasering)\nAT 62', 'Timebank payout\nWT 52', 'Time balance that is transferred to the next month (hours)', 'Dates vacation TAKEN', 'days \ntaken \nWT 99', 'Remaining holiday', 'EGENMELDING \nSelf-report days \nin the period\nAT 1\n\ndates', 'Sick leave days during the period\nAT 2 and 3\n\ndates', 'Sickness with \nmedical certificate\n\ndates', 'Sick child\nAT 10\n\ndates', 'Paid WT 14 /\n unpaid leave \nWT 15', 'Call-outs \n(to be payed)\nWT 432', 'Bonus incentives /\n other payouts \nWT 102', 'Comment \nbonus/other payout', 'Comments \npayroll']
Absence Template Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
Overtime Template Columns: ['Unnamed: 0', 'Unnamed: 1', 'Columns in yellow are mandatory', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', -1, 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16']

In [14]:
import openpyxl
import pandas as pd

# Load the workbook (data_only=True ensures we get the value, not formulas)
wb = openpyxl.load_workbook(input_excel_path, data_only=True)
sheet = wb.active

# 1. Extract the specific cells
employee_id = sheet["F2"].value
employee_name = sheet["B2"].value

print(f"Extracted Employee ID: {employee_id}")
print(f"Extracted Name: {employee_name}")

# 2. Get the EXACT column names from the Admin template 
# (This prevents NaN errors if the template has hidden spaces like "Ee ID ")
col_id = df_admin.columns[0]   # The first column in Admin.xlsx
col_name = df_admin.columns[1] # The second column in Admin.xlsx

# 3. Create a new row using the exact column names
new_admin_row = {
    col_id: employee_id,
    col_name: employee_name
}

# 4. Add the extracted data into df_admin
df_admin = pd.concat([df_admin, pd.DataFrame([new_admin_row])], ignore_index=True)

# Display the updated Admin DataFrame
print("\nUpdated Admin Template Data:")
display(df_admin)

Extracted Employee ID: 508
Extracted Name: Kjetil Haga

Updated Admin Template Data:

,Ee \nID,Name,Email address,Role,Delivered monthly \nreport \nYES/NO,Total overtime (hours),Overtime hours for pay out (HOURLY\nrate \nWT 118,Overtime \nadd\n50%\nWT 425,Overtime\n add \n100%\nWT 426,Overtime hours \nfor time off\nWT 61,...,Remaining holiday,EGENMELDING \nSelf-report days \nin the period\nAT 1\n\ndates,Sick leave days during the period\nAT 2 and 3\n\ndates,Sickness with \nmedical certificate\n\ndates,Sick child\nAT 10\n\ndates,Paid WT 14 /\n unpaid leave \nWT 15,Call-outs \n(to be payed)\nWT 432,Bonus incentives /\n other payouts \nWT 102,Comment \nbonus/other payout,Comments \npayroll
0,F2,B2,NaN,NaN,NaN,F36,G36 G = H+ I,H36,I36,starts with E4 and ends with E40 to check if s...,...,K41,"frp, q-U its corresponding to column J in exce...",if comments put up the dates here please .,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,508,Kjetil Haga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# Assuming 'sheet' and 'df_admin' are still active

def clean_val(val):
    if val is None or val == "-":
        return ""
    return str(val)

total_overtime = clean_val(sheet["F36"].value)

# For G36/H2+I2 logic
raw_overtime_payout = sheet["G36"].value 
if raw_overtime_payout is None or raw_overtime_payout == "-":
    try:
        h2 = sheet["H2"].value if isinstance(sheet["H2"].value, (int, float)) else 0
        i2 = sheet["I2"].value if isinstance(sheet["I2"].value, (int, float)) else 0
        overtime_payout = str(h2 + i2)
    except:
        overtime_payout = "0"
else:
    overtime_payout = clean_val(raw_overtime_payout)

overtime_50 = clean_val(sheet["H36"].value)
overtime_100 = clean_val(sheet["I36"].value)

# Time balance transferred
time_balance = clean_val(sheet["E40"].value)

# Vacation days and remaining
days_taken = clean_val(sheet["K36"].value)
remaining_holiday = clean_val(sheet["K41"].value)

# ----------------- FIXED TIMEBANK LOGIC -----------------
# Both columns will now strictly use E5 - E40 as requested.
e5_val = sheet["E5"].value if isinstance(sheet["E5"].value, (int, float)) else 0
e40_val = sheet["E40"].value if isinstance(sheet["E40"].value, (int, float)) else 0

# (E5 - E40) calculates to 20 - 20 = 0 based on the current Excel file
timebank_math_result = str(e5_val - e40_val)

# Assign the math result to the relevant columns
timebank_payout = timebank_math_result
time_off_withdrawal = timebank_math_result

# Overtime hours for time off (E38)
overtime_for_time_off = clean_val(sheet["E38"].value)
# --------------------------------------------------------

# Advanced Parsing for Dates (Rows 4 through 34)
vacation_dates = []
self_report_dates = []
sick_leave_dates = []

for row in range(4, 35):
    day_val = sheet[f"A{row}"].value
    
    if not isinstance(day_val, (int, float)):
        continue
        
    day_int = int(day_val)
    
    # Check Vacation (Column K)
    k_val = sheet[f"K{row}"].value
    if isinstance(k_val, (int, float)) and k_val > 0:
        vacation_dates.append(str(day_int))
        
    # Check Sick Leave / Absence (Column J) and Comments (Column D)
    j_val = sheet[f"J{row}"].value
    d_val = sheet[f"D{row}"].value
    
    if isinstance(j_val, (int, float)) and j_val > 0:
        if d_val and str(d_val).strip() != "":
            sick_leave_dates.append(str(day_int))
        else:
            self_report_dates.append(str(day_int))

vacation_dates_str = ", ".join(vacation_dates)
self_report_dates_str = ", ".join(self_report_dates)
sick_leave_dates_str = ", ".join(sick_leave_dates)

# Update the Last Row in df_admin
last_idx = df_admin.index[-1]
cols = df_admin.columns

df_admin.loc[last_idx, cols[5]] = total_overtime        
df_admin.loc[last_idx, cols[6]] = overtime_payout       
df_admin.loc[last_idx, cols[7]] = overtime_50           
df_admin.loc[last_idx, cols[8]] = overtime_100          

df_admin.loc[last_idx, cols[9]] = overtime_for_time_off 
df_admin.loc[last_idx, cols[10]] = time_off_withdrawal  
df_admin.loc[last_idx, cols[11]] = timebank_payout      

df_admin.loc[last_idx, cols[12]] = time_balance         
df_admin.loc[last_idx, cols[13]] = vacation_dates_str   
df_admin.loc[last_idx, cols[14]] = days_taken           
df_admin.loc[last_idx, cols[15]] = remaining_holiday    

df_admin.loc[last_idx, cols[16]] = self_report_dates_str 
df_admin.loc[last_idx, cols[17]] = sick_leave_dates_str  

print(f"Calculated value for E5 - E40 (applied to Timebank & Withdrawal columns): {timebank_math_result}")
print("\nFully Updated Admin Template:")
display(df_admin.iloc[:, :18])

Calculated value for E5 - E40 (applied to Timebank & Withdrawal columns): 0

Fully Updated Admin Template:

,Ee \nID,Name,Email address,Role,Delivered monthly \nreport \nYES/NO,Total overtime (hours),Overtime hours for pay out (HOURLY\nrate \nWT 118,Overtime \nadd\n50%\nWT 425,Overtime\n add \n100%\nWT 426,Overtime hours \nfor time off\nWT 61,Withdrawal of time off (avspasering)\nAT 62,Timebank payout\nWT 52,Time balance that is transferred to the next month (hours),Dates vacation TAKEN,days \ntaken \nWT 99,Remaining holiday,EGENMELDING \nSelf-report days \nin the period\nAT 1\n\ndates,Sick leave days during the period\nAT 2 and 3\n\ndates
0,F2,B2,NaN,NaN,NaN,F36,G36 G = H+ I,H36,I36,starts with E4 and ends with E40 to check if s...,E4 - E40,E4 - E40 [Check with the operations Ps],E40[check this out with the operations please],the Onces present in the column K and the date...,K36,K41,"frp, q-U its corresponding to column J in exce...",if comments put up the dates here please .
1,508,Kjetil Haga,NaN,NaN,NaN,- -,0,,,0,0,0,20,"9, 10, 11, 12, 15, 16, 17, 18, 19, 22, 23, 24,...",14,11,,

In [18]:
import pandas as pd
from datetime import datetime

# Assuming 'sheet' (from openpyxl) is still active from your input_excel
employee_id = clean_val(sheet["F2"].value)
employee_name = clean_val(sheet["B2"].value)

# Let's write a small helper function to group consecutive days.
# If an employee takes days 10, 11, 12, 13, 14, this groups them into "From 10" to "To 14" (5 days)
def group_consecutive_days(days_list):
    if not days_list:
        return []
        
    days_list = sorted([int(d) for d in days_list])
    groups = []
    
    start_day = days_list[0]
    prev_day = days_list[0]
    count = 1
    
    for day in days_list[1:]:
        if day == prev_day + 1:
            # It is consecutive
            count += 1
            prev_day = day
        else:
            # Gap found, save the previous group
            groups.append({"from": start_day, "to": prev_day, "days": count})
            start_day = day
            prev_day = day
            count = 1
            
    # Append the last group
    groups.append({"from": start_day, "to": prev_day, "days": count})
    return groups


# 1. First, we need to gather the actual days from the input sheet again
vacation_days = []
self_report_sick = [] # No comment in column D
cert_sick = []        # Has comment in column D

for row in range(4, 35):
    day_val = sheet[f"A{row}"].value
    if not isinstance(day_val, (int, float)):
        continue
        
    day_int = int(day_val)
    
    # Vacation
    k_val = sheet[f"K{row}"].value
    if isinstance(k_val, (int, float)) and k_val > 0:
        vacation_days.append(day_int)
        
    # Sick
    j_val = sheet[f"J{row}"].value
    d_val = sheet[f"D{row}"].value
    if isinstance(j_val, (int, float)) and j_val > 0:
        if d_val and str(d_val).strip() != "":
            cert_sick.append(day_int)
        else:
            self_report_sick.append(day_int)

# 2. Group the days
vacation_groups = group_consecutive_days(vacation_days)
self_report_groups = group_consecutive_days(self_report_sick)
cert_sick_groups = group_consecutive_days(cert_sick)

# 3. Create rows for the Absence template
# Looking at the template, the columns line up as:
# Index 1: 'ee nr'
# Index 2: 'Employee Name'
# Index 4: 'Absence type'
# Index 5: '%'
# Index 6: 'date from'
# Index 7: 'date to'
# Index 8: 'number of days'
# Index 9: 'Internal comment'

absence_rows = []

month_str = clean_val(sheet["I2"].value) # e.g. "Jun"
year_str = clean_val(sheet["J2"].value)  # e.g. "2026"

def format_date(day):
    # Formats the simple integer day into e.g. "10-Jun-2026"
    return f"{day}-{month_str}-{year_str}"

# Add Vacation rows
for grp in vacation_groups:
    row_data = [None] * len(df_absence.columns)
    row_data[1] = employee_id
    row_data[2] = employee_name
    row_data[4] = "Ferie (Vacation)"  # Or whatever code you use for vacation
    row_data[5] = "100%"
    row_data[6] = format_date(grp["from"])
    row_data[7] = format_date(grp["to"])
    row_data[8] = grp["days"]
    absence_rows.append(row_data)

# Add Self-Report Sick rows (Code 2 based on your template text)
for grp in self_report_groups:
    row_data = [None] * len(df_absence.columns)
    row_data[1] = employee_id
    row_data[2] = employee_name
    row_data[4] = "2" # "Code 2" from template instructions
    row_data[5] = "100%"
    row_data[6] = format_date(grp["from"])
    row_data[7] = format_date(grp["to"])
    row_data[8] = grp["days"]
    absence_rows.append(row_data)

# Add Certified Sick rows
for grp in cert_sick_groups:
    row_data = [None] * len(df_absence.columns)
    row_data[1] = employee_id
    row_data[2] = employee_name
    row_data[4] = "Syk med legeerklæring" # Sickness with medical certificate
    row_data[5] = "100%"
    row_data[6] = format_date(grp["from"])
    row_data[7] = format_date(grp["to"])
    row_data[8] = grp["days"]
    absence_rows.append(row_data)

# 4. Append to df_absence
if absence_rows:
    new_df = pd.DataFrame(absence_rows, columns=df_absence.columns)
    df_absence = pd.concat([df_absence, new_df], ignore_index=True)

print("Updated Absence Template Data (Showing the new rows):")
display(df_absence.tail(max(1, len(absence_rows))))

Updated Absence Template Data (Showing the new rows):

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
14,None,508,Kjetil Haga,None,Ferie (Vacation),100%,9-Jun-ÅR:,12-Jun-ÅR:,4,None,None,None,None,None
15,None,508,Kjetil Haga,None,Ferie (Vacation),100%,15-Jun-ÅR:,19-Jun-ÅR:,5,None,None,None,None,None
16,None,508,Kjetil Haga,None,Ferie (Vacation),100%,22-Jun-ÅR:,26-Jun-ÅR:,5,None,None,None,None,None

In [20]:
import pandas as pd

# Make sure we still have employee ID and name
employee_id = clean_val(sheet["F2"].value)
employee_name = clean_val(sheet["B2"].value)

# 1. Gather the exact values to check if they need an overtime row
# (We reuse the logic from the Admin template)

# WT 118: Overtime payout
raw_overtime_payout = sheet["G36"].value 
if raw_overtime_payout is None or raw_overtime_payout == "-":
    try:
        h2 = sheet["H2"].value if isinstance(sheet["H2"].value, (int, float)) else 0
        i2 = sheet["I2"].value if isinstance(sheet["I2"].value, (int, float)) else 0
        wt_118_val = h2 + i2
    except:
        wt_118_val = 0
else:
    wt_118_val = float(raw_overtime_payout) if str(raw_overtime_payout).replace('.','').isdigit() else 0

# WT 425: Overtime 50%
h36 = sheet["H36"].value
wt_425_val = float(h36) if str(h36).replace('.','').isdigit() else 0

# WT 426: Overtime 100%
i36 = sheet["I36"].value
wt_426_val = float(i36) if str(i36).replace('.','').isdigit() else 0

# WT 61: Overtime hours for time off
e38 = sheet["E38"].value
wt_61_val = float(e38) if str(e38).replace('.','').isdigit() else 0

# Timebank logic for WT 62 and WT 52 (E5 - E40 logic you specified)
e5_val = sheet["E5"].value if isinstance(sheet["E5"].value, (int, float)) else 0
e40_val = sheet["E40"].value if isinstance(sheet["E40"].value, (int, float)) else 0
timebank_math_result = e5_val - e40_val

wt_62_val = timebank_math_result  # Withdrawal of time off
wt_52_val = timebank_math_result  # Timebank payout

# 2. Define a list of possible wage codes and their names
# Format: (Wage Code, Wage Code Name, Value to write)
wage_entries = [
    (118, "Overtime hours for pay out", wt_118_val),
    (425, "Overtime add 50%", wt_425_val),
    (426, "Overtime add 100%", wt_426_val),
    (61,  "Overtime hours for time off", wt_61_val),
    (62,  "Withdrawal of time off", wt_62_val),
    (52,  "Timebank payout", wt_52_val)
]

# 3. Create rows for df_overtime ONLY if the value is not 0
overtime_rows = []
columns_length = len(df_overtime.columns)

for code, name, value in wage_entries:
    # Only add to the template if the employee actually has hours for this specific code!
    # (If you want to include 0 values, just remove the `if value != 0:` line)
    if value != 0:
        row_data = [None] * columns_length
        # Based on index 6 of the df_overtime, columns map like this:
        row_data[0] = employee_id         # Employee number
        row_data[1] = employee_name       # Name
        row_data[2] = code                # Wage code
        row_data[3] = name                # Wage code name
        row_data[5] = value               # Number of (hours)
        
        overtime_rows.append(row_data)

# 4. Append the rows to df_overtime
if overtime_rows:
    new_df = pd.DataFrame(overtime_rows, columns=df_overtime.columns)
    df_overtime = pd.concat([df_overtime, new_df], ignore_index=True)

print("Updated Overtime Template Data (Showing just the relevant columns):")
# Displaying specific index locations to make it readable, since the file has many blank columns
if not df_overtime.empty and len(df_overtime) > 7:
    display(df_overtime.iloc[7:, [0, 1, 2, 3, 5]])
else:
    print("No overtime entries were > 0, so no rows were added to the template for this employee.")

Updated Overtime Template Data (Showing just the relevant columns):

,Unnamed: 0,Unnamed: 1,Columns in yellow are mandatory,Unnamed: 3,Unnamed: 5
7,F2,B2,118,118 by default if there is anything in the co...,NaN
8,NaN,NaN,NaN,425 is column h2 id admin,NaN
9,NaN,NaN,NaN,426 is the column i2 of the admin sheet,NaN

In [22]:
import os
from datetime import datetime

# 1. Get the current date and time string
# Format: YYYY-MM-DD_HH-MM-SS
current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

# 2. Define the output directory
# We will save them in an "Outputs" folder inside your project directory to keep things organized.
output_dir = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs"

# Create the Outputs directory if it doesn't exist yet
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# 3. Define the new file paths with the date/time tag
admin_output_path = os.path.join(output_dir, f"Admin_{current_time}.xlsx")
absence_output_path = os.path.join(output_dir, f"Absense_{current_time}.xlsx")
overtime_output_path = os.path.join(output_dir, f"overtime_{current_time}.xlsx")

# 4. Save the DataFrames to Excel
# We use index=False so pandas doesn't write the row numbers (0, 1, 2) into the Excel file
df_admin.to_excel(admin_output_path, index=False)
df_absence.to_excel(absence_output_path, index=False)

# (If you mapped data into df_overtime earlier, it saves here too. If not, it saves the empty template)
df_overtime.to_excel(overtime_output_path, index=False)

# 5. Print a success message
print("✅ All files have been successfully saved!")
print(f"Admin saved to: {admin_output_path}")
print(f"Absence saved to: {absence_output_path}")
print(f"Overtime saved to: {overtime_output_path}")

✅ All files have been successfully saved!
Admin saved to: C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs\Admin_2026-07-24_21-26-59.xlsx
Absence saved to: C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs\Absense_2026-07-24_21-26-59.xlsx
Overtime saved to: C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs\overtime_2026-07-24_21-26-59.xlsx

In [24]:
import pandas as pd
import os
from datetime import datetime

# ==========================================
# 1. PROCESS OVERTIME TEMPLATE
# ==========================================
# Ensure we have employee ID and name
employee_id = clean_val(sheet["F2"].value)
employee_name = clean_val(sheet["B2"].value)

# Pulling the exact column headers from the Admin dataframe!
# These contain the exact strings you want like "Overtime \nadd\n50%\nWT 425"
admin_cols = df_admin.columns

header_118 = admin_cols[6]  # "Overtime hours for pay out (HOURLY\nrate \nWT 118"
header_425 = admin_cols[7]  # "Overtime \nadd\n50%\nWT 425"
header_426 = admin_cols[8]  # "Overtime\n add \n100%\nWT 426"
header_61  = admin_cols[9]  # "Overtime hours \nfor  time off\nWT 61"

# Convert values to float (Default to 0 if empty/invalid)
val_118 = float(overtime_payout) if overtime_payout and str(overtime_payout).replace('.','').isdigit() else 0
val_425 = float(overtime_50) if overtime_50 and str(overtime_50).replace('.','').isdigit() else 0
val_426 = float(overtime_100) if overtime_100 and str(overtime_100).replace('.','').isdigit() else 0
val_61  = float(overtime_for_time_off) if overtime_for_time_off and str(overtime_for_time_off).replace('.','').isdigit() else 0

# Define the rows mapping the specific Wage Codes to the exact Admin Header Strings
wage_entries = [
    (118, header_118, val_118),
    (425, header_425, val_425),
    (426, header_426, val_426),
    (61,  header_61,  val_61)
]

overtime_rows = []
columns_length = len(df_overtime.columns)

for code, header_text, value in wage_entries:
    row_data = [None] * columns_length
    row_data[0] = employee_id         # Employee number
    row_data[1] = employee_name       # Name
    row_data[2] = code                # Wage code
    
    # You requested the Admin column text go into the "Text" column (which is Index 4) 
    # Or "Wage code name" (which is Index 3). I am placing it in Index 3 and 4 just to be safe,
    # so it perfectly aligns with whatever variation the operations team uses.
    row_data[3] = header_text         # Wage code name (standard)
    row_data[4] = header_text         # Text (Detailed description)
    
    row_data[5] = value               # Number of (hours)
    
    overtime_rows.append(row_data)

# Append to df_overtime
if overtime_rows:
    new_df = pd.DataFrame(overtime_rows, columns=df_overtime.columns)
    df_overtime = pd.concat([df_overtime, new_df], ignore_index=True)


# ==========================================
# 2. SAVE ALL 3 DATAFRAMES INTO 1 EXCEL FILE
# ==========================================
current_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
output_dir = r"C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

# Define the single output file path
combined_output_path = os.path.join(output_dir, f"Final_Timesheet_Report_{current_time}.xlsx")

# Use pandas ExcelWriter to write multiple sheets to the same file
with pd.ExcelWriter(combined_output_path, engine='openpyxl') as writer:
    df_admin.to_excel(writer, sheet_name="Admin", index=False)
    df_absence.to_excel(writer, sheet_name="Absence", index=False)
    df_overtime.to_excel(writer, sheet_name="Overtime", index=False)

print("✅ SUCCESS!")
print(f"All three templates combined into one file:")
print(f"--> {combined_output_path}")

print("\nPreview of the newly added Overtime rows with Admin headers:")
# Columns 0 (ID), 1 (Name), 2 (Code), 3 (Wage code name/Admin text), 5 (Hours)
display(df_overtime.tail(4).iloc[:, [0, 1, 2, 3, 5]])

✅ SUCCESS!
All three templates combined into one file:
--> C:\Users\SohaibNM\OneDrive - Otis Global Tenant\Documents\Projects\Otis-qpa-ocr\Outputs\Final_Timesheet_Report_2026-07-24_21-33-50.xlsx

Preview of the newly added Overtime rows with Admin headers:

,Unnamed: 0,Unnamed: 1,Columns in yellow are mandatory,Unnamed: 3,Unnamed: 5
13,508,Kjetil Haga,118,Overtime hours for pay out (HOURLY\nrate \nWT 118,0.0
14,508,Kjetil Haga,425,Overtime \nadd\n50%\nWT 425,0.0
15,508,Kjetil Haga,426,Overtime\n add \n100%\nWT 426,0.0
16,508,Kjetil Haga,61,Overtime hours \nfor time off\nWT 61,0.0